"""Supabase adapter + squad sync (PRD §12).

The ONLY module that talks to the shared backend, mirroring how lcu.py is the
only module that talks to the League client. Uses Supabase's REST/Auth HTTP API
directly (no SDK) — the app already depends on `requests`, and this keeps the
surface small and inspectable.

The social model is zero-config and account-free (§12):
  * identity = the player's in-game PUUID (captured from the League client)
  * auth     = a silent Supabase *anonymous* session (no email/password)
  * squad    = your League friends who also run VibeCheck and list you back

There is nothing to sign up for and no code to share. With no backend
configured at all, everything here is inert and nothing leaves the machine.

Credentials: released builds bake the project URL + publishable key in at build
time (vibecheck/_bundled.py, gitignored). Self-hosters can drop a supabase.json
in %LOCALAPPDATA%\\LeagueOfKiffance. The publishable/anon key is public by
design; Row-Level Security in supabase/schema.sql is what protects the data.
"""

import json
import logging
import os
import threading
from datetime import datetime

import requests

from .config import DATA_DIR
from .store import GameStore

log = logging.getLogger(__name__)

CONFIG_PATH = DATA_DIR / "supabase.json"
SESSION_KEY = "supabase_session"  # anonymous session tokens, per machine
MY_PUUID_KEY = "my_puuid"
MY_NAME_KEY = "my_summoner_name"
TIMEOUT = 15


class SupabaseError(Exception):
    """Any backend failure, surfaced to the UI with a readable message."""


# ---------------------------------------------------------------- config


def _bundled_defaults() -> dict:
    """Credentials baked in at build time — what shipped releases use.

    `vibecheck/_bundled.py` is generated by the release build and is gitignored,
    so the repo never carries the key. End users therefore never enter anything:
    the app already points at the shared project (PRD §12).
    """
    try:
        from . import _bundled
    except ImportError:
        return {}
    url = getattr(_bundled, "SUPABASE_URL", "")
    key = getattr(_bundled, "SUPABASE_KEY", "")
    return {"url": url, "anon_key": key} if url and key else {}


def load_config() -> dict:
    """Resolve backend credentials, most specific first.

    1. the local config file — self-hosters and development
    2. build-time bundled defaults — the normal path for released builds
    3. environment variables — CI and scripted runs

    Returns {} when the backend isn't set up at all, which keeps the app fully
    local and silent.
    """
    try:
        cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
        if cfg.get("url") and cfg.get("anon_key"):
            return cfg
    except (OSError, ValueError):
        pass

    bundled = _bundled_defaults()
    if bundled:
        return bundled

    url = os.environ.get("VIBECHECK_SUPABASE_URL", "")
    key = os.environ.get("VIBECHECK_SUPABASE_KEY", "")
    return {"url": url, "anon_key": key} if url and key else {}


def save_config(url: str, anon_key: str) -> None:
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(
        json.dumps({"url": url.rstrip("/"), "anon_key": anon_key}, indent=2), encoding="utf-8"
    )
    log.info("Supabase config saved (%s)", url)


# ---------------------------------------------------------------- client


class Supabase:
    """Thin HTTP client for Supabase Auth + PostgREST."""

    def __init__(self, url: str, anon_key: str, session: dict | None = None, on_session=None):
        self.url = url.rstrip("/")
        self.anon_key = anon_key
        self.session = session or {}
        # Called every time the session changes, so the caller can save it
        # immediately. Supabase *rotates* the refresh token on every use: saving
        # only at the end of a successful operation means any error in between
        # loses the new token, and the next launch presents the old one — which
        # the server has already consumed ("Invalid Refresh Token: Already Used").
        self._on_session = on_session

    # -- auth --------------------------------------------------------

    @property
    def user_id(self) -> str | None:
        return (self.session.get("user") or {}).get("id")

    @property
    def logged_in(self) -> bool:
        return bool(self.session.get("access_token"))

    def _auth(self, path: str, payload: dict) -> dict:
        try:
            resp = requests.post(
                f"{self.url}/auth/v1/{path}",
                json=payload,
                headers={"apikey": self.anon_key, "Content-Type": "application/json"},
                timeout=TIMEOUT,
            )
        except requests.RequestException as exc:
            raise SupabaseError(
                f"Could not reach the backend — check your connection. ({exc.__class__.__name__})"
            ) from exc
        data = _json(resp)
        if resp.status_code >= 400:
            msg = (
                data.get("msg") or data.get("error_description") or data.get("message") or resp.text
            )
            raise SupabaseError(msg)
        if not data.get("access_token"):
            raise SupabaseError("Backend did not return a session token.")
        self._set_session(data)
        return data

    def _set_session(self, session: dict) -> None:
        self.session = session
        if not self._on_session:
            return
        try:
            self._on_session(session)
        except Exception:
            # Saving is best-effort: a write failure must not turn a successful
            # sign-in into a failed one.
            log.debug("Could not persist the session", exc_info=True)

    def sign_in_anonymous(self) -> dict:
        """Create a silent anonymous session (no email/password).

        Requires "Allow anonymous sign-ins" to be enabled in the Supabase
        project (Authentication → Sign In / Providers). If it's off, Supabase
        replies 422 and we surface that so the operator can flip it on.
        """
        return self._auth("signup", {})

    def refresh(self) -> dict:
        token = self.session.get("refresh_token")
        if not token:
            raise SupabaseError("no session to refresh")
        return self._auth("token?grant_type=refresh_token", {"refresh_token": token})

    def sign_out(self) -> None:
        # Persisted too, so a session we know is dead isn't reloaded next launch.
        self._set_session({})

    # -- data --------------------------------------------------------

    def _headers(self, extra: dict | None = None) -> dict:
        headers = {
            "apikey": self.anon_key,
            "Authorization": f"Bearer {self.session.get('access_token', self.anon_key)}",
            "Content-Type": "application/json",
        }
        headers.update(extra or {})
        return headers

    def _request(self, method: str, path: str, retry: bool = True, extra_headers=None, **kwargs):
        try:
            resp = requests.request(
                method,
                f"{self.url}/rest/v1/{path}",
                headers=self._headers(extra_headers),
                timeout=TIMEOUT,
                **kwargs,
            )
        except requests.RequestException as exc:
            raise SupabaseError(f"Could not reach the backend. ({exc.__class__.__name__})") from exc
        if resp.status_code == 401 and retry and self.session.get("refresh_token"):
            self.refresh()  # access tokens expire hourly
            # extra_headers must be forwarded, or the retried upsert loses its
            # Prefer: merge-duplicates and becomes a plain insert -> dup key.
            return self._request(method, path, retry=False, extra_headers=extra_headers, **kwargs)
        if resp.status_code >= 400:
            data = _json(resp)
            raise SupabaseError(data.get("message") or data.get("hint") or resp.text)
        return _json(resp)

    def select(self, table: str, params: dict) -> list:
        out = self._request("GET", table, params=params)
        return out if isinstance(out, list) else []

    def upsert(self, table: str, rows: list, on_conflict: str | None = None) -> None:
        if not rows:
            return
        params = {"on_conflict": on_conflict} if on_conflict else None
        self._request(
            "POST",
            table,
            params=params,
            json=rows,
            extra_headers={"Prefer": "resolution=merge-duplicates,return=minimal"},
        )

    def delete(self, table: str, params: dict) -> None:
        self._request("DELETE", table, params=params)


def _json(resp) -> dict:
    try:
        return resp.json() or {}
    except ValueError:
        return {}


# ---------------------------------------------------------------- service


class SquadService:
    """App-facing squad operations: identity, push, and mutual-friend reads.

    Everything is keyed on the in-game PUUID. Auth is a silent anonymous
    session used purely to satisfy Row-Level Security; users never see it.
    """

    def __init__(self, store: GameStore):
        self.store = store
        self._lock = threading.Lock()
        self._profile_synced = False
        cfg = load_config()
        session = {}
        raw = store.get_meta(SESSION_KEY)
        if raw:
            try:
                session = json.loads(raw)
            except ValueError:
                session = {}
        self.client = (
            Supabase(cfg["url"], cfg["anon_key"], session, on_session=self._save_session)
            if cfg.get("url") and cfg.get("anon_key")
            else None
        )

    # -- state -------------------------------------------------------

    @property
    def configured(self) -> bool:
        """Whether a backend is wired up at all (bundled creds, file, or env)."""
        return self.client is not None

    @property
    def my_puuid(self) -> str | None:
        return self.store.get_meta(MY_PUUID_KEY)

    def configure(self, url: str, anon_key: str) -> None:
        """Point at a self-hosted backend (advanced; released builds skip this)."""
        save_config(url, anon_key)
        self.client = Supabase(url, anon_key, on_session=self._save_session)
        self._profile_synced = False

    def _save_session(self, session: dict) -> None:
        """Write the session the moment it changes (see Supabase.on_session)."""
        self.store.set_meta(SESSION_KEY, json.dumps(session))

    def _persist_session(self) -> None:
        self._save_session(self.client.session)

    @staticmethod
    def _is_auth_error(exc: SupabaseError) -> bool:
        msg = str(exc).lower()
        return "refresh token" in msg or "jwt" in msg or "not signed in" in msg

    def _upsert_profile(self, puuid: str) -> None:
        name = self.store.get_meta(MY_NAME_KEY) or "Summoner"
        try:
            self.client.upsert(
                "profiles",
                [{"id": self.client.user_id, "puuid": puuid, "display_name": name}],
                on_conflict="id",
            )
        except SupabaseError as exc:
            # profiles.puuid must NOT be unique (see supabase/schema.sql): one
            # player legitimately owns a new row whenever their anonymous session
            # is recreated. A project carrying a leftover unique constraint from
            # an older schema breaks sync permanently for that player, and RLS
            # stops the client from clearing the old row — so say what to do
            # rather than surfacing a raw Postgres error.
            if "profiles_puuid_key" in str(exc):
                raise SupabaseError(
                    "The backend still has a unique constraint on profiles.puuid — "
                    "run supabase/fix-profiles-puuid-unique.sql in the project."
                ) from exc
            raise

    def _ensure_identity(self) -> None:
        """Guarantee a valid session + a profile linking it to our PUUID.

        Creates the anonymous session lazily, then upserts the profile once per
        process. If the stored session is unrecoverable (e.g. its refresh token
        was already used/rotated), it is discarded and a fresh anonymous session
        is created — otherwise sync would stay broken until the DB is wiped.
        Raises SupabaseError (surfaced to the UI) if the backend is missing or
        we don't yet know who the player is.
        """
        if not self.client:
            raise SupabaseError("Squad Online isn't set up on this build.")
        puuid = self.my_puuid
        if not puuid:
            raise SupabaseError(
                "Start the League client once so VibeCheck knows your in-game identity."
            )
        if not self.client.logged_in:
            self.client.sign_in_anonymous()
            self._profile_synced = False
        if not self._profile_synced:
            try:
                self._upsert_profile(puuid)
            except SupabaseError as exc:
                if not self._is_auth_error(exc):
                    raise
                log.info("Anonymous session invalid (%s); re-authenticating", exc)
                self.client.sign_out()
                self.client.sign_in_anonymous()
                self._upsert_profile(puuid)
            self._profile_synced = True
        # Persist now so any token the refresh flow rotated during the upsert is
        # saved — otherwise the next launch reloads a stale (already-used) token.
        self._persist_session()

    def status(self) -> dict:
        """Lightweight state for the Squad Online tab."""
        puuid = self.my_puuid
        cached_friends = self._cached_friend_puuids()
        out = {
            "configured": self.configured,
            "identity_ready": bool(puuid),
            "display_name": self.store.get_meta(MY_NAME_KEY),
            "friend_count": len(cached_friends),
            "mutual_count": 0,
            "synced": False,
        }
        if not self.configured or not puuid:
            return out
        try:
            data = self.friends_games()
            out["mutual_count"] = len([p for p in data["players"] if p != puuid])
            out["synced"] = True
        except SupabaseError as exc:
            out["error"] = str(exc)
        return out

    # -- friends -----------------------------------------------------

    def _cached_friend_puuids(self) -> list:
        try:
            return json.loads(self.store.get_meta("my_friends") or "[]")
        except ValueError:
            return []

    def push_friends(self, friend_puuids: list) -> None:
        """Mirror my current League friends list onto the backend as edges.

        Reconciles: adds new friends, removes edges for people no longer on the
        list, so an ex-friend stops being a mutual (and loses visibility).
        """
        self._ensure_identity()
        me = self.my_puuid
        current = {p for p in friend_puuids if p and p != me}
        self.store.set_meta("my_friends", json.dumps(sorted(current)))
        with self._lock:
            existing = {
                r["friend_puuid"]
                for r in self.client.select(
                    "friend_links", {"select": "friend_puuid", "owner_puuid": f"eq.{me}"}
                )
            }
            to_add = current - existing
            if to_add:
                self.client.upsert(
                    "friend_links",
                    [{"owner_puuid": me, "friend_puuid": f} for f in to_add],
                    on_conflict="owner_puuid,friend_puuid",
                )
            for gone in existing - current:
                self.client.delete(
                    "friend_links",
                    {"owner_puuid": f"eq.{me}", "friend_puuid": f"eq.{gone}"},
                )
            log.info(
                "Friend links synced: %d total (+%d/-%d)",
                len(current),
                len(to_add),
                len(existing - current),
            )
            self._persist_session()

    # -- sync --------------------------------------------------------

    def push(self) -> int:
        """Upsert my rated, non-skipped, non-remake games. Idempotent."""
        self._ensure_identity()
        me = self.my_puuid
        with self._lock:
            rows = [
                {
                    "puuid": me,
                    "riot_match_id": g["riot_match_id"],
                    "played_at": g["played_at"],
                    "queue_type": g["queue_type"],
                    "champion": g["champion"],
                    "role": g["role"],
                    "win": bool(g["win"]) if g["win"] is not None else None,
                    "kills": g["kills"],
                    "deaths": g["deaths"],
                    "assists": g["assists"],
                    "duration_seconds": g["duration_seconds"],
                    "fun_score": g["fun_score"],
                    "synced_at": datetime.now().astimezone().isoformat(timespec="seconds"),
                }
                for g in self.store.games_with_details()
                if g.get("fun_score")
                and not g.get("skipped")
                and not g.get("is_remake")
                and g.get("riot_match_id")
            ]
            self.client.upsert("shared_games", rows, on_conflict="puuid,riot_match_id")
            log.info("Synced %d rated games to the squad backend", len(rows))
            self._persist_session()
            return len(rows)

    def sync_all(self, friend_puuids: list) -> None:
        """Push friend edges then games — the full background sync on connect."""
        self.push_friends(friend_puuids)
        self.push()

    # -- shared reads ------------------------------------------------

    def friends_games(self) -> dict:
        """My games + every mutual friend's games, plus display names.

        RLS does the filtering: an unfiltered select returns only rows the
        caller is allowed to see (their own + mutual friends'), so we don't
        need to know the friend list to query — just to label the result.
        """
        self._ensure_identity()
        profiles = self.client.select("profiles", {"select": "puuid,display_name"})
        games = self.client.select(
            "shared_games",
            {"select": "puuid,riot_match_id,played_at,queue_type,champion,win,fun_score"},
        )
        self._persist_session()
        return {
            "me": self.my_puuid,
            "players": {p["puuid"]: p.get("display_name") or "Summoner" for p in profiles},
            "games": games,
        }
