"""Bake the shared backend credentials into the build (for local exe builds).

Reads the Supabase config already saved on this machine
(%LOCALAPPDATA%\\VibeCheck\\supabase.json) and writes
vibecheck/_bundled.py, which PyInstaller then includes so shipped builds point
at the shared project with no setup screen for friends.

`_bundled.py` is gitignored — the publishable key never enters the repo. CI
builds write the same file from GitHub secrets instead (see docs/RELEASE.md);
this tool is the local-build equivalent.

Run: .venv\\Scripts\\python tools\\bake_credentials.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from vibecheck.sync import CONFIG_PATH

BUNDLED = Path(__file__).resolve().parent.parent / "vibecheck" / "_bundled.py"


def main() -> None:
    try:
        cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        print(f"No saved config at {CONFIG_PATH}.")
        print("Set up Squad Online in the app first (enter your project URL + publishable key).")
        sys.exit(1)

    url, key = cfg.get("url", ""), cfg.get("anon_key", "")
    if not url or not key:
        print("Saved config is incomplete — need both url and anon_key.")
        sys.exit(1)

    if "service_role" in key or key.startswith("sb_secret"):
        # Guardrail: the secret key must never be shipped.
        print("That looks like a SECRET key. Only the publishable key may be bundled. Aborting.")
        sys.exit(1)

    BUNDLED.write_text(
        f'"""Generated by tools/bake_credentials.py — do not commit (gitignored)."""\n'
        f"SUPABASE_URL = {url!r}\n"
        f"SUPABASE_KEY = {key!r}\n",
        encoding="utf-8",
    )
    print(f"Wrote {BUNDLED}")
    print(f"  URL: {url}")
    print(f"  key: {key[:16]}… (publishable)")
    print("\nRebuild the exe and Squad Online will be zero-config for friends.")


if __name__ == "__main__":
    main()
